const lessonData = {};

lessonData["01_BlackHand.mp3"] = [{
    text: "The Black Hand was a secret military society formed in the country of Serbia. It was started in 1901 by officers in the Serbian army. The group was very nationalistic. This means they loved their country very much and wanted to unite all the territories where Serbian people lived. The members believed that violence was necessary to achieve their goals. They operated in the shadows, using secret codes and holding hidden meetings to plan their actions. Their most famous act changed the entire world. In 1914, the Black Hand helped a young man named Gavrilo Princip assassinate Archduke Franz Ferdinand in Sarajevo. The Archduke was the heir to the Austrian empire. This single murder was the spark that started World War I. The war caused the deaths of millions of people across the globe. The leader of the Black Hand was a man named Dragutin Dimitrijević, known as 'Apis.' He was eventually executed by his own government because he became too dangerous and powerful. The group is remembered for starting one of the biggest conflicts in history.",
    dict: { "secret": "gizli", "military": "askeri", "society": "cemiyet/toplum", "formed": "kuruldu/oluşturuldu", "officers": "subaylar", "nationalistic": "milliyetçi", "unite": "birleştirmek", "territories": "bölgeler/topraklar", "necessary": "gerekli", "achieve": "ulaşmak/başarmak", "shadows": "gölgeler", "hidden": "gizli", "meetings": "toplantılar", "plan": "planlamak", "actions": "eylemler", "famous": "ünlü", "act": "eylem/hareket", "entire": "bütün/tüm", "young": "genç", "assassinate": "suikast düzenlemek", "heir": "varis/veliaht", "empire": "imparatorluk", "single": "tek", "murder": "cinayet", "spark": "kıvılcım", "caused": "sebep oldu", "deaths": "ölümler", "globe": "küre/dünya", "leader": "lider", "eventually": "sonunda", "executed": "idam edildi", "dangerous": "tehlikeli", "powerful": "güçlü", "remembered": "hatırlanır", "starting": "başlatma", "conflicts": "çatışmalar" },
    questions: [ {q:"Was the Black Hand a secret military society?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they want to unite all Serbian territories?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they believe that violence was necessary?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they operate openly with no secret codes?", a_en:"No", a_tr:"Hayır"}, {q:"Did they help assassinate Archduke Franz Ferdinand?", a_en:"Yes", a_tr:"Evet"}, {q:"Did this murder start World War I?", a_en:"Yes", a_tr:"Evet"}, {q:"Was their leader executed by his own government?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_Boxers.mp3"] = [{
    text: "The Boxers were a secret society in China around the year 1900. Their Chinese name meant 'Righteous and Harmonious Fists.' Western people called them 'Boxers' because they practiced martial arts and physical exercises. The members of this group were very angry about foreign people in China. They hated the Christian missionaries and European traders who were changing their culture. The Boxers believed that their special training and rituals made them immune to bullets and swords. They thought modern weapons could do them no harm. This belief gave them the courage to fight against powerful armies. In 1900, they started a violent uprising called the Boxer Rebellion. They attacked foreign embassies in Beijing and killed many people. The Empress of China supported them for a short time. However, a large army from eight different countries invaded China to stop them. The Boxers were defeated because their magic protection offered no real defense. The rebellion ended in 1901, and China was forced to pay a huge amount of money to the foreign powers.",
    dict: { "secret": "gizli", "society": "cemiyet", "meant": "anlamına geliyordu", "Righteous": "Adil/Doğru", "Harmonious": "Uyumlu", "Fists": "Yumruklar", "Western": "Batılı", "practiced": "uyguladılar/yaptılar", "martial arts": "dövüş sanatları", "physical": "fiziksel", "exercises": "egzersizler", "angry": "öfkeli", "foreign": "yabancı", "hated": "nefret ettiler", "Christian": "Hristiyan", "missionaries": "misyonerler", "traders": "tüccarlar", "changing": "değiştiren", "culture": "kültür", "believed": "inandılar", "special": "özel", "training": "eğitim", "rituals": "ritüeller", "immune": "bağışık/etkilenmez", "bullets": "mermiler", "swords": "kılıçlar", "weapons": "silahlar", "harm": "zarar", "belief": "inanç", "courage": "cesaret", "fight": "savaşmak", "powerful": "güçlü", "armies": "ordular", "violent": "şiddetli", "uprising": "ayaklanma", "Rebellion": "İsyan", "attacked": "saldırdılar", "embassies": "büyükelçilikler", "killed": "öldürdüler", "Empress": "İmparatoriçe", "supported": "destekledi", "short": "kısa", "invaded": "işgal etti", "stop": "durdurmak", "defeated": "yenildiler", "magic": "sihir/büyü", "protection": "koruma", "offered": "sundu/sağladı", "defense": "savunma", "forced": "zorlandı", "pay": "ödemek", "huge": "kocaman", "amount": "miktar" },
    questions: [ {q:"Were the Boxers a secret society in China?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Western people call them Boxers because they practiced martial arts?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they hate foreign people in China?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they think modern weapons could do them no harm?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Empress of China support them forever?", a_en:"No", a_tr:"Hayır"}, {q:"Did their magic protection offer no real defense?", a_en:"Yes", a_tr:"Evet"}, {q:"Was China forced to pay a huge amount of money?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["03_Camorra.mp3"] = [{
    text: "The Camorra is a criminal organization from Italy. It started in the city of Naples around the 17th century. It is even older than the famous Sicilian Mafia. The Camorra began as a secret gang inside prisons to protect inmates. Later, it moved out into the city streets. The group is no single organization with one boss. Instead, it is made of many different clans or families. These families control specific neighborhoods and often fight each other for power. This makes them very violent and unpredictable. In the past, they acted like a shadow government. They helped poor people when the real government failed, but they also demanded money for protection. If a shop owner paid nothing, the Camorra would hurt them or destroy their business. Today, they are still very powerful. They are involved in illegal activities like drug trafficking and waste disposal. They have a strict code of silence. The Camorra remains a dangerous force in southern Italy, controlling many aspects of daily life through fear.",
    dict: { "criminal": "suçlu/kriminal", "organization": "örgüt/kuruluş", "older": "daha eski", "famous": "ünlü", "began": "başladı", "gang": "çete", "inside": "içinde", "prisons": "hapishaneler", "protect": "korumak", "inmates": "mahkumlar", "Later": "Daha sonra", "streets": "sokaklar", "single": "tek", "boss": "patron", "Instead": "Bunun yerine", "different": "farklı", "clans": "klanlar", "families": "aileler", "control": "kontrol etmek", "specific": "belirli", "neighborhoods": "mahalleler", "often": "sık sık", "power": "güç", "violent": "şiddetli", "unpredictable": "öngörülemez", "past": "geçmiş", "acted": "davrandı", "shadow": "gölge", "poor": "fakir", "failed": "başarısız oldu", "demanded": "talep etti", "protection": "koruma", "owner": "sahip", "paid": "ödedi", "nothing": "hiçbir şey", "hurt": "incitmek/zarar vermek", "destroy": "yok etmek", "business": "iş", "Today": "Bugün", "involved": "karışmış/dahil olan", "illegal": "yasadışı", "activities": "faaliyetler", "drug": "uyuşturucu", "trafficking": "kaçakçılık", "waste": "atık/çöp", "disposal": "bertaraf/yok etme", "strict": "sıkı/katı", "code": "kural/kod", "silence": "sessizlik", "remains": "kalır/olmaya devam eder", "dangerous": "tehlikeli", "force": "güç/kuvvet", "southern": "güney", "aspects": "yönler/açılar", "daily": "günlük", "fear": "korku" },
    questions: [ {q:"Is the Camorra a criminal organization from Italy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did it begin inside prisons to protect inmates?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the group a single organization with one boss?", a_en:"No", a_tr:"Hayır"}, {q:"Do different families fight each other for power?", a_en:"Yes", a_tr:"Evet"}, {q:"If a shop owner paid nothing, would they destroy the business?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they involved in illegal waste disposal?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they have a strict code of silence?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_Carbonari.mp3"] = [{
    text: "The Carbonari were a secret network of revolutionaries in Italy in the 1800s. Their name means 'Charcoal Burners.' They were called this because they met in secret places like forests where people made charcoal. They were no criminals like the Mafia. They were political fighters. They wanted Italy to be a free and united country with a constitution. At that time, Italy was divided and ruled by foreign kings. The Carbonari wanted to overthrow these kings. They had secret handshakes and complex rituals to protect their members. Many important Italian patriots were members. They organized revolts and protests against the government. Although they failed many times and were often arrested or executed, their ideas survived. They helped prepare the people for the eventual unification of Italy. They are remembered as brave men who fought for freedom and democracy in secret. Their work laid the foundation for modern Italy.",
    dict: { "network": "ağ", "revolutionaries": "devrimciler", "means": "anlamına gelir", "Charcoal": "Kömür", "Burners": "Yakanlar", "called": "adlandırıldı", "met": "buluştular", "places": "yerler", "forests": "ormanlar", "criminals": "suçlular", "political": "siyasi", "fighters": "savaşçılar", "free": "özgür", "united": "birleşik", "country": "ülke", "constitution": "anayasa", "divided": "bölünmüş", "ruled": "yönetilen", "foreign": "yabancı", "kings": "krallar", "overthrow": "devirmek", "handshakes": "el sıkışmalar", "complex": "karmaşık", "rituals": "ritüeller", "members": "üyeler", "important": "önemli", "patriots": "vatanseverler", "organized": "organize ettiler", "revolts": "isyanlar", "protests": "protestolar", "against": "karşı", "government": "hükümet", "Although": "rağmen", "failed": "başarısız oldular", "arrested": "tutuklandılar", "executed": "idam edildiler", "ideas": "fikirler", "survived": "hayatta kaldı", "prepare": "hazırlamak", "eventual": "nihai/sonunda olan", "unification": "birleşme", "remembered": "hatırlanır", "brave": "cesur", "fought": "savaştılar", "freedom": "özgürlük", "democracy": "demokrasi", "work": "iş/çalışma", "laid": "koydu/attı", "foundation": "temel", "modern": "modern" },
    questions: [ {q:"Were the Carbonari a secret network of revolutionaries?", a_en:"Yes", a_tr:"Evet"}, {q:"Does their name mean 'Charcoal Burners'?", a_en:"Yes", a_tr:"Evet"}, {q:"Were they criminals like the Mafia?", a_en:"No", a_tr:"Hayır"}, {q:"Did they want Italy to be a united country?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they want to overthrow foreign kings?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use secret handshakes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did their ideas survive to help prepare Italy for unification?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["05_Freemasons.mp3"] = [{
    text: "The Freemasons are one of the most well-known secret societies in the world. They started in Europe hundreds of years ago. Originally, they were groups of stonemasons who built the great cathedrals and castles. They had secret signs and handshakes to prove they were skilled workers. Over time, the group changed. They became a social club for men who wanted to discuss new ideas. They focused on brotherhood, charity, and moral improvement. Many famous people were Freemasons, including George Washington and Mozart. Because they held secret meetings and had strange rituals, many people became suspicious of them. The Catholic Church and various kings banned them. People thought the Freemasons were plotting against the government or religion. There are many conspiracy theories about them. Some people believe they secretly run the world or hide ancient treasures. However, most historians say they are just a fraternal organization that does good things for the community. Despite this, their secrecy continues to make people curious.",
    dict: { "well-known": "iyi bilinen", "societies": "cemiyetler", "originally": "başlangıçta", "groups": "gruplar", "stonemasons": "taş ustaları", "built": "inşa ettiler", "great": "harika/büyük", "cathedrals": "katedraller", "castles": "kaleler", "signs": "işaretler", "prove": "kanıtlamak", "skilled": "yetenekli/vasıflı", "workers": "işçiler", "Over time": "Zamanla", "changed": "değişti", "became": "oldu", "social": "sosyal", "club": "kulüp", "discuss": "tartışmak", "focused": "odaklandı", "brotherhood": "kardeşlik", "charity": "hayır kurumu/yardım", "moral": "ahlaki", "improvement": "gelişim", "famous": "ünlü", "including": "dahil olmak üzere", "suspicious": "şüpheli", "banned": "yasakladı", "plotting": "komplo kurmak", "religion": "din", "conspiracy": "komplo", "theories": "teoriler", "secretly": "gizlice", "run": "yönetmek", "hide": "saklamak", "ancient": "antik/eski", "treasures": "hazineler", "historians": "tarihçiler", "fraternal": "kardeşlik", "community": "toplum", "Despite": "rağmen", "secrecy": "gizlilik", "continues": "devam eder", "curious": "meraklı" },
    questions: [ {q:"Did the Freemasons start as groups of stonemasons?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use secret signs to prove they were skilled workers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they eventually become a social club?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Catholic Church encourage them to grow?", a_en:"No", a_tr:"Hayır"}, {q:"Do some people believe they secretly run the world?", a_en:"Yes", a_tr:"Evet"}, {q:"Do historians say they are an evil organization?", a_en:"No", a_tr:"Hayır"}, {q:"Does their secrecy continue to make people curious?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_Hashashin.mp3"] = [{
    text: "The Hashashin were a secret order in the Middle East during the Middle Ages. They lived in mountain fortresses in Persia and Syria. Their most famous castle was called Alamut. Their leader was known as the 'Old Man of the Mountain.' The Hashashin were a small group, so they could fight no big wars. Instead, they used a terrifying method to reach their goals: murder. They sent highly trained agents to kill kings, generals, and religious leaders who were their enemies. These agents were very patient. They would wait for years to get close to their target. They often used daggers to kill in public places to create maximum fear. The English word 'assassin' comes from their name. There were stories that they used a drug called hashish to prepare for their missions, but many historians think this is a myth. They were so feared that powerful rulers paid them money to stay safe. Their power lasted for almost 200 years. Finally, in the 13th century, the Mongol armies destroyed their castles and ended their rule.",
    dict: { "order": "tarikat/düzen", "Middle Ages": "Orta Çağ", "lived": "yaşadılar", "mountain": "dağ", "fortresses": "kaleler", "castle": "kale", "leader": "lider", "small": "küçük", "terrifying": "korkunç", "method": "yöntem", "reach": "ulaşmak", "goals": "hedefler", "murder": "cinayet", "sent": "gönderdiler", "highly": "yüksek derecede", "trained": "eğitimli", "agents": "ajanlar", "generals": "generaller", "religious": "dini", "enemies": "düşmanlar", "patient": "sabırlı", "wait": "beklemek", "close": "yakın", "target": "hedef", "daggers": "hançerler", "public": "halka açık", "create": "yaratmak", "maximum": "maksimum", "fear": "korku", "word": "kelime", "assassin": "suikastçı", "comes": "gelir", "drug": "uyuşturucu", "prepare": "hazırlanmak", "missions": "görevler", "myth": "efsane/mit", "feared": "korkulan", "rulers": "hükümdarlar", "paid": "ödedi", "safe": "güvenli", "lasted": "sürdü", "destroyed": "yok etti", "ended": "bitirdi", "rule": "yönetim" },
    questions: [ {q:"Were the Hashashin a secret order in the Middle East?", a_en:"Yes", a_tr:"Evet"}, {q:"Was their leader known as the 'Old Man of the Mountain'?", a_en:"Yes", a_tr:"Evet"}, {q:"Could they fight big wars easily?", a_en:"No", a_tr:"Hayır"}, {q:"Did they use murder to reach their goals?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the English word 'assassin' come from their name?", a_en:"Yes", a_tr:"Evet"}, {q:"Did powerful rulers pay them money to stay safe?", a_en:"Yes", a_tr:"Evet"}, {q:"Did their rule last forever without ending?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["07_Illuminati.mp3"] = [{
    text: "The Illuminati is a name that appears in many modern conspiracy theories. The real group was called the Bavarian Illuminati. It was founded in 1776 by a man named Adam Weishaupt in Germany. Weishaupt was a professor who wanted to promote reason and science. He liked nothing about the power of the church or the monarchy. He wanted a society where people were free from religious prejudice. The group was very secretive and had a complex system of ranks. They recruited members from other societies. However, the Illuminati lasted for no long period. The ruler of Bavaria banned all secret societies in 1785. The group was broken up, and its members were scattered. Despite this short history, the idea of the Illuminati never died. Today, many people believe the group still exists. They think the Illuminati is a shadow government that controls the world banks and the media. There is no proof for these stories, but the legend lives on. The name is still used to describe a powerful, hidden elite.",
    dict: { "appears": "görünür", "modern": "modern", "real": "gerçek", "founded": "kuruldu", "professor": "profesör", "promote": "teşvik etmek", "reason": "akıl/mantık", "science": "bilim", "nothing": "hiçbir şey", "power": "güç", "church": "kilise", "monarchy": "monarşi", "free": "özgür", "religious": "dini", "prejudice": "önyargı", "secretive": "gizli", "complex": "karmaşık", "system": "sistem", "ranks": "rütbeler", "recruited": "işe aldı/üye yaptı", "societies": "cemiyetler", "lasted": "sürdü", "period": "dönem", "ruler": "hükümdar", "banned": "yasakladı", "broken up": "parçalandı/dağıtıldı", "scattered": "dağıldı", "short": "kısa", "history": "tarih", "died": "öldü", "exists": "var olmak", "shadow": "gölge", "government": "hükümet", "controls": "kontrol eder", "banks": "bankalar", "media": "medya", "proof": "kanıt", "stories": "hikayeler", "legend": "efsane", "describe": "tanımlamak", "hidden": "gizli", "elite": "seçkin" },
    questions: [ {q:"Was the real group called the Bavarian Illuminati?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the founder want to promote reason and science?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he like nothing about the power of the church?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Illuminati last for a very long period?", a_en:"No", a_tr:"Hayır"}, {q:"Did the ruler of Bavaria ban all secret societies in 1785?", a_en:"Yes", a_tr:"Evet"}, {q:"Is there proof that they control the world banks today?", a_en:"No", a_tr:"Hayır"}, {q:"Is the name still used to describe a hidden elite?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_KnightsHospitaller.mp3"] = [{
    text: "The Knights Hospitaller was a military and religious order that started in the 11th century. Originally, they were no warriors. They were a group of monks who ran a hospital in Jerusalem to care for poor and sick pilgrims. When the Crusades began, they changed. They became knights who fought to protect the Holy Land. They wore black coats with a white cross. After the Christians lost Jerusalem, the Hospitallers moved to the island of Rhodes and later to Malta. They became experts at naval warfare. They built great castles and had a powerful navy. They fought against the Ottoman Empire and pirates in the Mediterranean Sea. They were like a small, independent country with their own laws. The order was very wealthy and powerful for hundreds of years. In 1798, Napoleon Bonaparte captured their island of Malta. Today, the order still exists, but they have returned to their original mission. They focus on charity and medical care around the world.",
    dict: { "military": "askeri", "religious": "dini", "order": "tarikat/düzen", "started": "başladı", "century": "yüzyıl", "warriors": "savaşçılar", "monks": "keşişler", "ran": "yönetti/işletti", "hospital": "hastane", "care": "bakmak/ilgilenmek", "poor": "fakir", "sick": "hasta", "pilgrims": "hacılar", "Crusades": "Haçlı Seferleri", "began": "başladı", "changed": "değiştiler", "knights": "şövalyeler", "fought": "savaştılar", "protect": "korumak", "Holy": "Kutsal", "Land": "Toprak", "wore": "giydiler", "black": "siyah", "coats": "paltolar", "white": "beyaz", "cross": "haç", "lost": "kaybettiler", "moved": "taşındılar", "island": "ada", "experts": "uzmanlar", "naval": "deniz", "warfare": "savaş (sanatı)", "built": "inşa ettiler", "castles": "kaleler", "navy": "donanma", "pirates": "korsanlar", "independent": "bağımsız", "laws": "yasalar", "wealthy": "zengin", "captured": "ele geçirdi", "exists": "var olmak", "returned": "geri döndü", "original": "orijinal", "focus": "odaklanmak", "charity": "hayır kurumu/yardım", "medical": "tıbbi" },
    questions: [ {q:"Were the Knights Hospitaller originally warriors?", a_en:"No", a_tr:"Hayır"}, {q:"Did they start as a group of monks running a hospital?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they wear black coats with a white cross?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they move to the islands of Rhodes and Malta?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they become experts at naval warfare?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they have their own laws like an independent country?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they focus on fighting wars today?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["09_KnightsSaintLazarus.mp3"] = [{
    text: "The Order of Saint Lazarus is a unique order of knights from the Crusades. They started in Jerusalem as a hospital to treat people with leprosy. Leprosy is a terrible skin disease that causes deformities. In the Middle Ages, people with this disease were usually outcasts and forced to live away from society. However, this order welcomed knights who had leprosy. These 'Leper Knights' were very brave. They fought in battles alongside healthy soldiers. Because they were already dying from their disease, they feared no death on the battlefield. They were known to be very dangerous warriors. They wore a green cross on their chests. After the Crusades ended, the order moved to Europe. Over time, they stopped being a military group. They focused only on charity and helping the sick. The order still exists today as a humanitarian organization. They are remembered for their courage and for giving dignity to people with a dreaded disease.",
    dict: { "unique": "benzersiz", "treat": "tedavi etmek", "leprosy": "cüzzam", "terrible": "korkunç", "skin": "deri/cilt", "disease": "hastalık", "causes": "sebep olur", "deformities": "deformasyonlar", "Middle Ages": "Orta Çağ", "usually": "genellikle", "outcasts": "dışlanmışlar", "forced": "zorlandı", "away": "uzakta", "society": "toplum", "welcomed": "hoş karşıladı", "brave": "cesur", "battles": "savaşlar", "alongside": "yanında", "healthy": "sağlıklı", "soldiers": "askerler", "already": "zaten", "dying": "ölen", "feared": "korktular", "death": "ölüm", "battlefield": "savaş alanı", "dangerous": "tehlikeli", "warriors": "savaşçılar", "green": "yeşil", "chests": "göğüsler", "ended": "bitti", "stopped": "durdular/bıraktılar", "focused": "odaklandılar", "charity": "yardım", "helping": "yardım etme", "sick": "hasta", "humanitarian": "insani", "organization": "organizasyon", "remembered": "hatırlanır", "courage": "cesaret", "giving": "verme", "dignity": "onur/haysiyet", "dreaded": "korkulan" },
    questions: [ {q:"Did the order start as a hospital for people with leprosy?", a_en:"Yes", a_tr:"Evet"}, {q:"Were people with leprosy usually outcasts in the Middle Ages?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the order welcome knights who had leprosy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they fear death on the battlefield?", a_en:"No", a_tr:"Hayır"}, {q:"Did they wear a green cross on their chests?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they still a military fighting group today?", a_en:"No", a_tr:"Hayır"}, {q:"Did they give dignity to people with a dreaded disease?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_KnightsHolySepulchre.mp3"] = [{
    text: "The Order of the Holy Sepulchre is a very old Catholic order. It was created to protect the 'Holy Grave' (the tomb of Jesus) in Jerusalem. It started around the year 1099 during the First Crusade. The leader of the Crusaders, Godfrey of Bouillon, formed a group of knights to guard the most sacred place in Christianity. Unlike the Templars who lived like monks, these knights were often nobles who served the King of Jerusalem. They were fierce warriors who defended the city. After the Crusaders lost Jerusalem, the order changed. It stopped being a military army and became an honorary group. Today, the Pope leads the order. They are no longer soldiers. They wear white capes with a red cross. Their main job now is to send money to support Christians and schools in the Holy Land. They are a symbol of the link between Europe and the holy sites in Jerusalem.",
    dict: { "Catholic": "Katolik", "created": "yaratıldı/oluşturuldu", "protect": "korumak", "Grave": "Mezar", "tomb": "mezar", "First": "Birinci", "leader": "lider", "formed": "kurdu", "guard": "korumak/nöbet tutmak", "sacred": "kutsal", "place": "yer", "Christianity": "Hristiyanlık", "Unlike": "Aksine/Farklı olarak", "monks": "keşişler", "often": "sık sık", "nobles": "soylular", "served": "hizmet etti", "King": "Kral", "fierce": "şiddetli/vahşi", "warriors": "savaşçılar", "defended": "savundu", "city": "şehir", "changed": "değişti", "honorary": "onursal", "Pope": "Papa", "leads": "yönetir/liderlik eder", "no longer": "artık değil", "soldiers": "askerler", "wear": "giyerler", "white": "beyaz", "capes": "pelerinler", "red": "kırmızı", "cross": "haç", "main": "ana", "job": "iş", "send": "göndermek", "money": "para", "support": "desteklemek", "schools": "okullar", "symbol": "sembol", "link": "bağlantı", "between": "arasında", "sites": "alanlar/yerler" },
    questions: [ {q:"Was the order created to protect the tomb of Jesus?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the leader of the Crusaders form this group of knights?", a_en:"Yes", a_tr:"Evet"}, {q:"Were these knights often nobles who served the King?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they still a fierce military army today?", a_en:"No", a_tr:"Hayır"}, {q:"Does the Pope lead the order today?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they wear white capes with a red cross?", a_en:"Yes", a_tr:"Evet"}, {q:"Is their main job now to send money to support Christians?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["11_KnightsTemplar.mp3"] = [{
    text: "The Knights Templar is perhaps the most famous warrior order in history. They were founded around 1119 after the First Crusade. Their original job was to protect Christian pilgrims traveling to Jerusalem. They were monks, but they were also fierce soldiers. They wore white mantles with a red cross. The Templars became incredibly powerful. They received gifts of money and land from kings and nobles. They created the first international banking system. A pilgrim could leave money in Europe and get it back in Jerusalem. This made the Templars very rich. However, their wealth made people jealous. King Philip IV of France owed them a lot of money. He decided to destroy them. On Friday the 13th in 1307, he arrested hundreds of Templars. He accused them of terrible crimes and tortured them. The Pope dissolved the order in 1312. The sudden fall of this powerful group created many legends about lost treasures and secrets.",
    dict: { "perhaps": "belki de", "famous": "ünlü", "warrior": "savaşçı", "founded": "kuruldu", "original": "orijinal", "protect": "korumak", "pilgrims": "hacılar", "traveling": "seyahat eden", "monks": "keşişler", "fierce": "şiddetli/vahşi", "soldiers": "askerler", "mantles": "pelerinler", "incredibly": "inanılmaz derecede", "powerful": "güçlü", "received": "aldılar", "gifts": "hediyeler", "land": "toprak", "kings": "krallar", "nobles": "soylular", "created": "yarattılar", "international": "uluslararası", "banking": "bankacılık", "system": "sistem", "leave": "bırakmak", "rich": "zengin", "wealth": "zenginlik/servet", "jealous": "kıskanç", "owed": "borçluydu", "decided": "karar verdi", "destroy": "yok etmek", "arrested": "tutukladı", "hundreds": "yüzlerce", "accused": "suçladı", "terrible": "korkunç", "crimes": "suçlar", "tortured": "işkence etti", "dissolved": "dağıttı/feshetti", "sudden": "ani", "fall": "düşüş", "legends": "efsaneler", "lost": "kayıp", "treasures": "hazineler", "secrets": "sırlar" },
    questions: [ {q:"Was the original job of the Templars to protect Christian pilgrims?", a_en:"Yes", a_tr:"Evet"}, {q:"Were they both monks and fierce soldiers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they create the first international banking system?", a_en:"Yes", a_tr:"Evet"}, {q:"Did their wealth make people happy for them?", a_en:"No", a_tr:"Hayır"}, {q:"Did King Philip IV of France owe them money?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he arrest and torture hundreds of Templars?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Pope refuse to dissolve the order?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["12_KuKluxKlan.mp3"] = [{
    text: "The Ku Klux Klan, often called the KKK, is a hate group in the United States. It was started in 1865 after the American Civil War. The founders were former soldiers from the South who had lost the war. They accepted nothing about slavery ending. The Klan wanted to maintain white supremacy. Members wore white robes and pointed hoods to hide their faces and look like ghosts. They used extreme violence and terror. They burned crosses near people's houses to scare them. They beat and murdered African Americans and their white supporters. This is called lynching. The government tried to stop them, and the group disappeared for a while. However, it came back in the 1920s with millions of members. They also hated immigrants, Catholics, and Jewish people. Although their numbers are much smaller today, they still exist. They are considered a terrorist organization by many because of their history of violence and hatred based on race.",
    dict: { "often": "sık sık", "called": "adlandırılan", "hate": "nefret", "group": "grup", "started": "başlatıldı", "Civil War": "İç Savaş", "founders": "kurucular", "former": "eski/önceki", "soldiers": "askerler", "South": "Güney", "lost": "kaybetti", "accepted": "kabul etti", "nothing": "hiçbir şey", "slavery": "kölelik", "ending": "bitiş", "maintain": "sürdürmek", "white supremacy": "beyaz üstünlüğü", "Members": "Üyeler", "robes": "cübbeler", "pointed": "sivri", "hoods": "kukuletalar", "hide": "gizlemek", "faces": "yüzler", "ghosts": "hayaletler", "extreme": "aşırı", "violence": "şiddet", "terror": "terör", "burned": "yaktılar", "crosses": "haçlar", "scare": "korkutmak", "beat": "dövdüler", "murdered": "öldürdüler", "supporters": "destekçiler", "lynching": "linç etme", "government": "hükümet", "disappeared": "kayboldu", "while": "bir süre", "millions": "milyonlarca", "immigrants": "göçmenler", "smaller": "daha küçük", "exist": "var olmak", "considered": "kabul edilir", "terrorist": "terörist", "organization": "organizasyon", "history": "tarih", "hatred": "nefret", "based on": "dayalı", "race": "ırk" },
    questions: [ {q:"Is the KKK a hate group in the United States?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the founders accept nothing about slavery ending?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they wear pointed hoods to hide their faces?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use peace and love to spread their message?", a_en:"No", a_tr:"Hayır"}, {q:"Did they burn crosses near people's houses?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they hate immigrants and Catholics too?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they considered a terrorist organization today?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_LivonianBrothers.mp3"] = [{
    text: "The Livonian Brothers of the Sword were a ruthless order of knights. They were formed in 1202 in the region that is now Latvia and Estonia. Their job was to convert the pagan people of the Baltic area to Christianity. Unlike other orders that protected pilgrims, these knights were conquerors. They were known for being very cruel. They fought to take land and force people to change their religion. They wore white cloaks with a red sword and cross. They showed no consistent discipline and often fought for their own gain. In 1236, they were badly defeated in a battle by local tribes. Because they lost so many men, the survivors had to join the Teutonic Knights. They are remembered as the 'Warrior Monks' of the north who used extreme force to build a state. Their history is full of violence and conflict with the local people.",
    dict: { "ruthless": "acımasız", "order": "tarikat/düzen", "formed": "kuruldu", "region": "bölge", "convert": "dönüştürmek", "pagan": "putperest", "area": "alan/bölge", "Unlike": "Aksine", "protected": "koruyan", "pilgrims": "hacılar", "conquerors": "fatihler/işgalciler", "known": "bilinen", "cruel": "zalim", "fought": "savaştılar", "take": "almak", "land": "toprak", "force": "zorlamak", "change": "değiştirmek", "religion": "din", "cloaks": "pelerinler", "sword": "kılıç", "cross": "haç", "showed": "gösterdiler", "no": "hiç/yok", "consistent": "tutarlı", "discipline": "disiplin", "gain": "kazanç", "badly": "kötü bir şekilde", "defeated": "yenildiler", "battle": "savaş", "local": "yerel", "tribes": "kabileler", "Because": "Çünkü", "survivors": "hayatta kalanlar", "join": "katılmak", "remembered": "hatırlanır", "Warrior": "Savaşçı", "Monks": "Keşişler", "extreme": "aşırı", "build": "inşa etmek", "state": "devlet", "history": "tarih", "full": "dolu", "violence": "şiddet", "conflict": "çatışma" },
    questions: [ {q:"Were the Livonian Brothers a ruthless order of knights?", a_en:"Yes", a_tr:"Evet"}, {q:"Was their job to convert the pagan people to Christianity?", a_en:"Yes", a_tr:"Evet"}, {q:"Were they known for being very kind?", a_en:"No", a_tr:"Hayır"}, {q:"Did they wear white cloaks with a red sword?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they show no consistent discipline?", a_en:"Yes", a_tr:"Evet"}, {q:"Were they badly defeated by local tribes?", a_en:"Yes", a_tr:"Evet"}, {q:"Is their history full of peace and love?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["14_Ninja.mp3"] = [{
    text: "The Ninja, also known as Shinobi, were covert agents in feudal Japan. They were active from the 15th to the 17th century. Unlike the Samurai, who fought openly and followed a strict code of honor, the Ninja operated in secret. They were spies, assassins, and saboteurs. Their job was to do the dirty work that the Samurai could in no way do. Ninjas were experts in disguise. They could dress as farmers or monks to sneak into enemy castles. They used special tools and weapons, like throwing stars and smoke bombs. They were also masters of gathering information. The Ninja lived in hidden mountain villages and trained from childhood. Their skills were called Ninjutsu. Many legends say they could walk on water or become invisible, but these are just stories. In reality, they were highly skilled mercenaries who used psychology and stealth to win. When Japan became peaceful in the 17th century, the need for Ninjas disappeared. They faded into history, but they became famous characters in stories.",
    dict: { "known": "bilinen", "covert": "gizli", "agents": "ajanlar", "feudal": "feodal", "active": "aktif", "century": "yüzyıl", "Unlike": "Aksine/Farklı olarak", "openly": "açıkça", "followed": "takip ettiler", "strict": "sıkı/katı", "code": "kural/kod", "honor": "onur", "operated": "hareket ettiler/çalıştılar", "secret": "gizli", "spies": "casuslar", "assassins": "suikastçılar", "saboteurs": "sabotajcılar", "dirty": "kirli", "in no way": "hiçbir şekilde", "experts": "uzmanlar", "disguise": "kılık değiştirme", "dress": "giyinmek", "farmers": "çiftçiler", "sneak": "gizlice girmek", "enemy": "düşman", "castles": "kaleler", "tools": "araçlar", "weapons": "silahlar", "throwing stars": "fırlatma yıldızları", "smoke": "duman", "masters": "ustalar", "gathering": "toplama", "information": "bilgi", "hidden": "gizli", "villages": "köyler", "childhood": "çocukluk", "skills": "yetenekler", "legends": "efsaneler", "invisible": "görünmez", "reality": "gerçeklik", "highly": "yüksek derecede", "mercenaries": "paralı askerler", "psychology": "psikoloji", "stealth": "gizlilik", "win": "kazanmak", "peaceful": "barışçıl", "need": "ihtiyaç", "disappeared": "kayboldu", "faded": "soldu/silindi", "characters": "karakterler" },
    questions: [ {q:"Were the Ninja covert agents in feudal Japan?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they fight openly like the Samurai?", a_en:"No", a_tr:"Hayır"}, {q:"Could they do the dirty work the Samurai could in no way do?", a_en:"Yes", a_tr:"Evet"}, {q:"Were they experts in disguise?", a_en:"Yes", a_tr:"Evet"}, {q:"Could they actually become invisible like ghosts?", a_en:"No", a_tr:"Hayır"}, {q:"Were they highly skilled mercenaries?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the need for Ninjas disappear when Japan became peaceful?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["15_OpusDei.mp3"] = [{
    text: "Opus Dei is an institution within the Catholic Church. The name is Latin for 'Work of God.' It was founded in Spain in 1928 by a priest named Josemaría Escrivá. The group teaches that ordinary life and work can be a path to holiness. Members are encouraged to work hard and follow strict religious discipline. Most members are normal people with jobs, but some live in special houses and remain unmarried. Opus Dei became very controversial in the 20th century. Critics said it offered no transparency and was too controlling. Some former members said they were forced to cut ties with their families and give all their money to the group. They also practice 'mortification,' which means causing themselves small physical pain to feel closer to Jesus. The organization became very influential in politics and business, especially in Spain. Fiction books like 'The Da Vinci Code' portrayed them as dangerous villains, which increased their fame. While the church supports them, many people still view Opus Dei with suspicion.",
    dict: { "institution": "kurum", "within": "içinde", "Church": "Kilise", "Latin": "Latince", "Work": "İş", "God": "Tanrı", "founded": "kuruldu", "priest": "rahip", "teaches": "öğretir", "ordinary": "sıradan", "path": "yol", "holiness": "kutsallık", "encouraged": "teşvik edilir", "strict": "sıkı", "religious": "dini", "discipline": "disiplin", "normal": "normal", "remain": "kalır", "unmarried": "bekar", "controversial": "tartışmalı", "century": "yüzyıl", "Critics": "Eleştirmenler", "offered": "sundu", "no": "hiç/yok", "transparency": "şeffaflık", "controlling": "kontrolcü", "former": "eski", "forced": "zorlandı", "cut ties": "bağları koparmak", "practice": "uygular", "mortification": "nefis köreltme", "causing": "sebep olma", "physical": "fiziksel", "pain": "acı", "feel": "hissetmek", "closer": "daha yakın", "influential": "etkili", "politics": "politika", "business": "iş", "Fiction": "Kurgu", "portrayed": "tasvir etti", "dangerous": "tehlikeli", "villains": "kötü adamlar", "increased": "artırdı", "fame": "ün", "supports": "destekler", "view": "görür", "suspicion": "şüphe" },
    questions: [ {q:"Is Opus Dei an institution within the Catholic Church?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the name mean 'Work of God' in Latin?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they teach that ordinary work can be a path to holiness?", a_en:"Yes", a_tr:"Evet"}, {q:"Did critics say it offered no transparency?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they practice mortification to feel physical pleasure?", a_en:"No", a_tr:"Hayır"}, {q:"Are they very influential in politics and business?", a_en:"Yes", a_tr:"Evet"}, {q:"Do all people view them with complete trust?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["16_OrderDragon.mp3"] = [{
    text: "The Order of the Dragon was a monarchical chivalric order. It was founded in 1408 by Sigismund, the King of Hungary. The purpose of the order was to defend Christianity against enemies, especially the Ottoman Turks. The members were powerful knights and nobles. They wore a symbol of a dragon with its tail wrapped around its neck. This symbol represented the defeat of evil. The order was no secret society like the others, but it was an elite group of powerful men. The most famous member was Vlad II, the ruler of Wallachia. Because he was a member of the Order of the Dragon, he took the name 'Dracul,' which means 'The Dragon.' His son was Vlad III, also known as Vlad the Impaler. He became the inspiration for the vampire legend of Dracula. The Order of the Dragon was a political tool for the King to keep his nobles loyal. After the King died, the order slowly lost its importance. It is remembered today mostly because of its connection to the legend of Dracula.",
    dict: { "monarchical": "monarşik", "chivalric": "şövalye", "order": "tarikat/düzen", "founded": "kuruldu", "purpose": "amaç", "defend": "savunmak", "enemies": "düşmanlar", "powerful": "güçlü", "knights": "şövalyeler", "nobles": "soylular", "wore": "giydiler", "symbol": "sembol", "dragon": "ejderha", "tail": "kuyruk", "wrapped": "sarılmış", "neck": "boyun", "represented": "temsil ediyordu", "defeat": "yenilgi", "evil": "kötülük", "no": "hiç/değil", "secret": "gizli", "society": "cemiyet", "elite": "seçkin", "famous": "ünlü", "ruler": "hükümdar", "took": "aldı", "means": "anlamına gelir", "Impaler": "Kazıklı", "inspiration": "ilham", "vampire": "vampir", "legend": "efsane", "political": "siyasi", "tool": "araç", "keep": "tutmak", "loyal": "sadık", "died": "öldü", "slowly": "yavaşça", "lost": "kaybetti", "importance": "önem", "remembered": "hatırlanır", "mostly": "çoğunlukla", "connection": "bağlantı" },
    questions: [ {q:"Was the purpose of the order to defend Christianity?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they wear a symbol of a dragon?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the order no secret society like the others?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Vlad II take the name 'Dracul'?", a_en:"Yes", a_tr:"Evet"}, {q:"Was his son the inspiration for the werewolf legend?", a_en:"No", a_tr:"Hayır"}, {q:"Was the order a political tool to keep nobles loyal?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the order become more important after the King died?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["17_SicilianMafia.mp3"] = [{
    text: "The Sicilian Mafia, also known as Cosa Nostra ('Our Thing'), is a criminal syndicate from the island of Sicily in Italy. It started in the 19th century. Originally, they were groups of men who protected land when the police were too weak. Soon, they began to demand money for this protection. The Mafia is built on family connections. They have a strict hierarchy with a 'Don' or 'Godfather' at the top. The most important rule is 'Omertà,' the code of silence. A member must never talk to the authorities. If they do, they are killed. The Mafia became very powerful and infiltrated the government. In the early 20th century, many members moved to the United States and started powerful crime families there. They were involved in gambling, alcohol smuggling, and later drug trafficking. In the 1990s, the Italian government fought a war against them after they killed two famous judges. While many bosses were arrested, the Mafia still exists today, operating in the shadows.",
    dict: { "known as": "olarak bilinen", "criminal": "suçlu", "syndicate": "sendika/örgüt", "island": "ada", "century": "yüzyıl", "Originally": "Başlangıçta", "protected": "korudu", "weak": "zayıf", "Soon": "Yakında/Kısa süre sonra", "demand": "talep etmek", "built": "inşa edilmiş", "connections": "bağlantılar", "strict": "sıkı/katı", "hierarchy": "hiyerarşi", "Godfather": "Baba", "top": "en üst", "rule": "kural", "silence": "sessizlik", "member": "üye", "never": "asla", "talk": "konuşmak", "authorities": "yetkililer", "killed": "öldürülür", "powerful": "güçlü", "infiltrated": "sızdı", "government": "hükümet", "early": "erken", "moved": "taşındı", "started": "başlattı", "involved": "karışmış", "gambling": "kumar", "alcohol": "alkol", "smuggling": "kaçakçılık", "trafficking": "kaçakçılık", "fought": "savaştı", "judges": "hakimler", "arrested": "tutuklandı", "exists": "var olmak", "operating": "faaliyet gösteren", "shadows": "gölgeler" },
    questions: [ {q:"Is the Sicilian Mafia also known as Cosa Nostra?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they originally protect land when the police were weak?", a_en:"Yes", a_tr:"Evet"}, {q:"Is their most important rule 'Omertà', the code of silence?", a_en:"Yes", a_tr:"Evet"}, {q:"Can a member talk safely to the authorities?", a_en:"No", a_tr:"Hayır"}, {q:"Did many members move to the United States?", a_en:"Yes", a_tr:"Evet"}, {q:"Were they involved in gambling and smuggling?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Mafia completely destroyed today?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["18_TeutonicKnights.mp3"] = [{
    text: "The Teutonic Knights were a German military order founded in the 12th century. Like the Templars, they started during the Crusades to run a hospital for German pilgrims. Soon, they became a military force. They wore white coats with a black cross. After the Crusades in the Middle East failed, they moved to Europe. They launched the 'Northern Crusades' to convert the pagan people of the Baltic region to Christianity. They were very ruthless warriors. They conquered the land that became Prussia. They built huge brick castles and ruled the land as a state. They were no mere monks; they were rulers. They forced the local people to become Christians or face death. Their power grew until they threatened the neighboring countries. In 1410, a combined army of Polish and Lithuanian forces defeated them at the Battle of Tannenberg. This was one of the biggest battles in the Middle Ages. The order slowly lost its military power but still exists today as a charitable organization.",
    dict: { "military": "askeri", "order": "tarikat/düzen", "founded": "kuruldu", "century": "yüzyıl", "started": "başladı", "Crusades": "Haçlı Seferleri", "run": "yönetmek/işletmek", "hospital": "hastane", "pilgrims": "hacılar", "force": "güç", "wore": "giydiler", "coats": "paltolar", "cross": "haç", "failed": "başarısız oldu", "launched": "başlattılar", "convert": "dönüştürmek", "pagan": "putperest", "ruthless": "acımasız", "warriors": "savaşçılar", "conquered": "fethettiler", "built": "inşa ettiler", "brick": "tuğla", "castles": "kaleler", "ruled": "yönettiler", "state": "devlet", "no": "hiç/değil", "mere": "sadece/basit", "monks": "keşişler", "rulers": "hükümdarlar", "forced": "zorladılar", "local": "yerel", "face": "yüzleşmek", "death": "ölüm", "power": "güç", "grew": "büyüdü", "threatened": "tehdit etti", "neighboring": "komşu", "combined": "birleşik", "army": "ordu", "forces": "kuvvetler", "defeated": "yenildi", "Battle": "Savaş", "slowly": "yavaşça", "lost": "kaybetti", "exists": "var olmak", "charitable": "hayır amaçlı", "organization": "organizasyon" },
    questions: [ {q:"Did the Teutonic Knights start by running a hospital?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they wear white coats with a black cross?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they launch the Northern Crusades?", a_en:"Yes", a_tr:"Evet"}, {q:"Were they no mere monks but actual rulers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they ask nicely for people to change religion?", a_en:"No", a_tr:"Hayır"}, {q:"Were they defeated at the Battle of Tannenberg?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they still exist today as a charitable organization?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["19_Thuggee.mp3"] = [{
    text: "The Thuggee were a secret cult of assassins in India. The English word 'thug' comes from their name. They operated for hundreds of years, from the 14th to the 19th century. The Thuggee were travelers who worshipped the goddess Kali. They believed that killing people was a religious duty. They would join groups of travelers on the roads. They would act friendly and travel with them for days to gain their trust. Then, at a secret signal, they would attack. They usually used a handkerchief or scarf to strangle their victims. This was a silent way to kill. They would bury the bodies and steal their belongings. It is estimated that they killed tens of thousands of people over the centuries. They were very organized and had their own secret language. The British colonial government in India was horrified by them. In the 1830s, the British hunted them down and destroyed the network. The Thuggee are known as the world's first mafia.",
    dict: { "secret": "gizli", "cult": "tarikat", "assassins": "suikastçılar", "word": "kelime", "comes": "gelir", "operated": "faaliyet gösterdiler", "hundreds": "yüzlerce", "travelers": "gezginler", "worshipped": "taptılar", "goddess": "tanrıça", "believed": "inandılar", "killing": "öldürme", "religious": "dini", "duty": "görev", "join": "katılmak", "groups": "gruplar", "roads": "yollar", "friendly": "arkadaşça", "gain": "kazanmak", "trust": "güven", "signal": "sinyal", "attack": "saldırmak", "usually": "genellikle", "used": "kullandılar", "handkerchief": "mendil", "scarf": "atkı/eşarp", "strangle": "boğmak", "victims": "kurbanlar", "silent": "sessiz", "way": "yol/yöntem", "bury": "gömmek", "bodies": "cesetler", "steal": "çalmak", "belongings": "eşyalar", "estimated": "tahmin ediliyor", "tens": "onlarca", "centuries": "yüzyıllar", "organized": "organize", "own": "kendi", "language": "dil", "colonial": "sömürge", "government": "hükümet", "horrified": "dehşete düşmüş", "hunted": "avladılar", "destroyed": "yok ettiler", "network": "ağ", "known": "bilinen", "world": "dünya" },
    questions: [ {q:"Were the Thuggee a secret cult in India?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the word 'thug' come from their name?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they believe killing people was a bad thing?", a_en:"No", a_tr:"Hayır"}, {q:"Did they act friendly to gain travelers' trust?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use a scarf to strangle their victims?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they kill tens of thousands of people?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the British colonial government support them?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["20_Triads.mp3"] = [{
    text: "The Triads are Chinese transnational criminal organizations. They originated as secret societies in the 17th century. At first, they were patriotic groups. Their goal was to overthrow the Qing Dynasty and restore the old Ming Dynasty. They used secret codes and hand signs to identify each other. Over time, their purpose changed. When the Qing Dynasty fell in 1912, the Triads lost their political goal. They turned to crime to survive. Today, they are based in Hong Kong, Taiwan, and mainland China, but they operate all over the world. They are involved in illegal gambling, drug trafficking, and human smuggling. Unlike the Mafia, the Triads are no single organization. They are a collection of many different groups that share similar rituals and symbols. They are known for their distinct tattoos and use of numerology. For example, the number 36 represents the 36 oaths a member must take. They remain a powerful force in the criminal underworld of Asia.",
    dict: { "transnational": "ulusötesi", "criminal": "suçlu", "organizations": "örgütler", "originated": "ortaya çıktı", "secret": "gizli", "societies": "cemiyetler", "century": "yüzyıl", "patriotic": "vatansever", "goal": "hedef", "overthrow": "devirmek", "Dynasty": "Hanedanlık", "restore": "restore etmek/geri getirmek", "codes": "kodlar/şifreler", "signs": "işaretler", "identify": "tanımlamak/tanımak", "each other": "birbirlerini", "purpose": "amaç", "changed": "değişti", "fell": "düştü/yıkıldı", "lost": "kaybetti", "political": "siyasi", "turned": "döndüler", "crime": "suç", "survive": "hayatta kalmak", "based": "merkezli", "operate": "faaliyet gösterirler", "involved": "dahil/karışmış", "illegal": "yasadışı", "gambling": "kumar", "drug": "uyuşturucu", "trafficking": "kaçakçılık", "human": "insan", "smuggling": "kaçakçılık", "Unlike": "Aksine", "no": "hiç/değil", "single": "tek", "collection": "koleksiyon", "share": "paylaşır", "similar": "benzer", "rituals": "ritüeller", "symbols": "semboller", "distinct": "belirgin/farklı", "tattoos": "dövmeler", "numerology": "numeroloji", "represents": "temsil eder", "oaths": "yeminler", "member": "üye", "must": "zorunda", "take": "almak/etmek", "remain": "kalır", "force": "güç", "underworld": "yeraltı dünyası" },
    questions: [ {q:"Did the Triads originate as secret societies?", a_en:"Yes", a_tr:"Evet"}, {q:"Was their original goal to overthrow the Qing Dynasty?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they turn to crime to survive?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they based only in Europe?", a_en:"No", a_tr:"Hayır"}, {q:"Are the Triads no single organization, but a collection of groups?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they known for distinct tattoos and numerology?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the number 36 represent the oaths a member must take?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["21_Yakuza.mp3"] = [{
    text: "The Yakuza are members of transnational organized crime syndicates in Japan. They are similar to the Mafia but have a very different style. The Yakuza trace their origins to the 17th century, starting as peddlers and gamblers. They follow a strict code of behavior that resembles the samurai code. Yakuza members are famous for their full-body tattoos. These tattoos are traditional and painful to get. They are often hidden under clothes. Another famous practice is 'yubitsume.' If a member makes a mistake, they must cut off the tip of their little finger to show an apology to their boss. The Yakuza are in no way completely illegal in Japan. They have office buildings and business cards. They operate in a gray area. They run businesses like construction and entertainment, but also engage in extortion and blackmail. They see themselves as protectors of the traditional Japanese way. However, the police have cracked down on them in recent years.",
    dict: { "transnational": "ulusötesi", "organized": "organize", "crime": "suç", "syndicates": "sendikalar/örgütler", "similar": "benzer", "different": "farklı", "style": "stil/tarz", "trace": "izini sürer", "origins": "kökenler", "century": "yüzyıl", "peddlers": "işportacılar", "gamblers": "kumarbazlar", "follow": "takip eder", "strict": "sıkı", "code": "kural/kod", "behavior": "davranış", "resembles": "benzer", "famous": "ünlü", "full-body": "tüm vücut", "tattoos": "dövmeler", "traditional": "geleneksel", "painful": "acı verici", "hidden": "gizli", "practice": "uygulama", "mistake": "hata", "cut off": "kesmek", "tip": "uç", "finger": "parmak", "show": "göstermek", "apology": "özür", "boss": "patron", "in no way": "hiçbir şekilde", "completely": "tamamen", "illegal": "yasadışı", "office": "ofis", "buildings": "binalar", "cards": "kartlar", "operate": "faaliyet gösterirler", "gray": "gri", "area": "alan", "run": "yönetir/işletir", "businesses": "işletmeler", "construction": "inşaat", "entertainment": "eğlence", "engage": "ilgilene/yapmak", "extortion": "haraç/zorla alma", "blackmail": "şantaj", "protectors": "koruyucular", "way": "yol/tarz", "police": "polis", "cracked down": "baskı yaptı", "recent": "son", "years": "yıllar" },
    questions: [ {q:"Are the Yakuza organized crime syndicates in Japan?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they start as peddlers and gamblers?", a_en:"Yes", a_tr:"Evet"}, {q:"Are their full-body tattoos painless to get?", a_en:"No", a_tr:"Hayır"}, {q:"Must they cut off a finger tip if they make a mistake?", a_en:"Yes", a_tr:"Evet"}, {q:"Are the Yakuza in no way completely illegal in Japan?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they run businesses like construction?", a_en:"Yes", a_tr:"Evet"}, {q:"Has the police cracked down on them in recent years?", a_en:"Yes", a_tr:"Evet"} ]
}];
